// AUTO-GENERATED by gen-calendar.mjs from Notion — do not edit by hand.
// PLACEHOLDER: this is the committed fallback so the .ics feed's `import calendar from '../_calendar.js'`
// always resolves, even on the first deploy before gen-calendar.mjs has run. The generator overwrites
// this file (as functions/api/_calendar.js) on every publish with the live snapshot.
export default { meta: { schema: 'calendar/1', placeholder: true }, events: [], birthdays: [] };
