// functions/api/app/_aki-picks.js
// FROZEN historical picks — Aki 2026 banzuke prediction game.
// Compiled from the crew's Google Sheet (Master + per-player bonus tabs), picks FINAL.
// Immutable: this is the answer set the app grades once the Aki banzuke drops.
// Codes: y=Yokozuna o=Ozeki s=Sekiwake k=Komusubi m1..m18=Maegashira j=Juryo r=Retired.
// Reused shape for any basho: { basho, bashoId, wrestlers[], players[{key,name,ranks{},bonus[]}] }.

export default {
  "basho": "Aki 2026",
  "bashoId": "202609",
  "wrestlers": [
    "Hoshoryu",
    "Onosato",
    "Kirishima",
    "Kotozakura",
    "Atamifuji",
    "Kotoshoho",
    "Aonishiki",
    "Wakatakakage",
    "Oho",
    "Yoshinofuji",
    "Fujinokawa",
    "Takanosho",
    "Churanoumi",
    "Gonoyama",
    "Hakunofuji",
    "Hiradoumi",
    "Daieisho",
    "Ichiyamamoto",
    "Oshoma",
    "Ura",
    "Fujiseiun",
    "Shodai",
    "Kotoeiho",
    "Takayasu",
    "Roga",
    "Wakamotoharu",
    "Fujiryoga",
    "Tobizaru",
    "Asanoyama",
    "Chiyoshoma",
    "Mitakeumi",
    "Wakanosho",
    "Abi",
    "Asahakuryu",
    "Nishikifuji",
    "Takerufuji",
    "Kinbozan",
    "Shishi",
    "Kazuma",
    "Onokatsu",
    "Asakoryu",
    "Daiseizan"
  ],
  "players": [
    {
      "key": "jennie",
      "name": "Jennie",
      "ranks": {
        "Hoshoryu": "y",
        "Onosato": "y",
        "Kirishima": "o",
        "Kotozakura": "o",
        "Atamifuji": "s",
        "Kotoshoho": "k",
        "Aonishiki": "o",
        "Wakatakakage": "m9",
        "Oho": "m7",
        "Yoshinofuji": "m2",
        "Fujinokawa": "k",
        "Takanosho": "m4",
        "Churanoumi": "m3",
        "Gonoyama": "m4",
        "Hakunofuji": "m1",
        "Hiradoumi": "m8",
        "Daieisho": "m1",
        "Ichiyamamoto": "m6",
        "Oshoma": "m6",
        "Ura": "m9",
        "Fujiseiun": "m7",
        "Shodai": "m10",
        "Kotoeiho": "m3",
        "Takayasu": "m2",
        "Roga": "m5",
        "Wakamotoharu": "m11",
        "Fujiryoga": "m5",
        "Tobizaru": "m13",
        "Asanoyama": "m8",
        "Chiyoshoma": "m15",
        "Mitakeumi": "m17",
        "Wakanosho": "m15",
        "Abi": "m14",
        "Asahakuryu": "m14",
        "Nishikifuji": "m10",
        "Takerufuji": "m11",
        "Kinbozan": "m12",
        "Shishi": "m12",
        "Kazuma": "j",
        "Onokatsu": "j",
        "Asakoryu": "m13",
        "Daiseizan": "j"
      },
      "bonus": [
        {
          "name": "Shonannoumi",
          "rank": "m16"
        },
        {
          "name": "Asasuiryu",
          "rank": "m16"
        },
        {
          "name": "Toshinofuji",
          "rank": "m17"
        },
        {
          "name": "Arashifuji",
          "rank": "m17"
        }
      ]
    },
    {
      "key": "mj",
      "name": "MJ",
      "ranks": {
        "Hoshoryu": "y",
        "Onosato": "y",
        "Kirishima": "o",
        "Kotozakura": "o",
        "Atamifuji": "s",
        "Kotoshoho": "m2",
        "Aonishiki": "o",
        "Wakatakakage": "m5",
        "Oho": "m6",
        "Yoshinofuji": "m2",
        "Fujinokawa": "k",
        "Takanosho": "m4",
        "Churanoumi": "m3",
        "Gonoyama": "m3",
        "Hakunofuji": "k",
        "Hiradoumi": "m10",
        "Daieisho": "s",
        "Ichiyamamoto": "m7",
        "Oshoma": "m6",
        "Ura": "m10",
        "Fujiseiun": "m7",
        "Shodai": "m11",
        "Kotoeiho": "m1",
        "Takayasu": "m1",
        "Roga": "m5",
        "Wakamotoharu": "m11",
        "Fujiryoga": "m4",
        "Tobizaru": "m14",
        "Asanoyama": "m8",
        "Chiyoshoma": "m15",
        "Mitakeumi": "m17",
        "Wakanosho": "m14",
        "Abi": "m13",
        "Asahakuryu": "m13",
        "Nishikifuji": "m9",
        "Takerufuji": "m9",
        "Kinbozan": "m12",
        "Shishi": "m8",
        "Kazuma": "j",
        "Onokatsu": "j",
        "Asakoryu": "m12",
        "Daiseizan": "j"
      },
      "bonus": []
    },
    {
      "key": "sherry",
      "name": "Sherry",
      "ranks": {
        "Hoshoryu": "y",
        "Onosato": "y",
        "Kirishima": "o",
        "Kotozakura": "o",
        "Atamifuji": "s",
        "Kotoshoho": "m2",
        "Aonishiki": "o",
        "Wakatakakage": "m5",
        "Oho": "m6",
        "Yoshinofuji": "m2",
        "Fujinokawa": "k",
        "Takanosho": "m4",
        "Churanoumi": "m3",
        "Gonoyama": "m3",
        "Hakunofuji": "k",
        "Hiradoumi": "m10",
        "Daieisho": "s",
        "Ichiyamamoto": "m7",
        "Oshoma": "m6",
        "Ura": "m10",
        "Fujiseiun": "m7",
        "Shodai": "m11",
        "Kotoeiho": "m1",
        "Takayasu": "m1",
        "Roga": "m5",
        "Wakamotoharu": "m12",
        "Fujiryoga": "m4",
        "Tobizaru": "m14",
        "Asanoyama": "m8",
        "Chiyoshoma": "m15",
        "Mitakeumi": "j",
        "Wakanosho": "m14",
        "Abi": "m13",
        "Asahakuryu": "m13",
        "Nishikifuji": "m9",
        "Takerufuji": "m9",
        "Kinbozan": "m11",
        "Shishi": "m8",
        "Kazuma": "j",
        "Onokatsu": "j",
        "Asakoryu": "m12",
        "Daiseizan": "j"
      },
      "bonus": [
        {
          "name": "Asasoiryu",
          "rank": "m15"
        },
        {
          "name": "Tokihoyate",
          "rank": "m16"
        },
        {
          "name": "Toshinofiju",
          "rank": "m16"
        },
        {
          "name": "Shananoumi",
          "rank": "m17"
        }
      ]
    },
    {
      "key": "james",
      "name": "James",
      "ranks": {
        "Hoshoryu": "y",
        "Onosato": "y",
        "Kirishima": "o",
        "Kotozakura": "o",
        "Atamifuji": "s",
        "Kotoshoho": "m3",
        "Aonishiki": "o",
        "Wakatakakage": "m8",
        "Oho": "m6",
        "Yoshinofuji": "m2",
        "Fujinokawa": "s",
        "Takanosho": "m4",
        "Churanoumi": "m2",
        "Gonoyama": "m3",
        "Hakunofuji": "m1",
        "Hiradoumi": "m8",
        "Daieisho": "m1",
        "Ichiyamamoto": "m5",
        "Oshoma": "m4",
        "Ura": "m9",
        "Fujiseiun": "m7",
        "Shodai": "m9",
        "Kotoeiho": "k",
        "Takayasu": "k",
        "Roga": "m6",
        "Wakamotoharu": "m10",
        "Fujiryoga": "m5",
        "Tobizaru": "m12",
        "Asanoyama": "m7",
        "Chiyoshoma": "m14",
        "Mitakeumi": "r",
        "Wakanosho": "m12",
        "Abi": "m13",
        "Asahakuryu": "m15",
        "Nishikifuji": "m11",
        "Takerufuji": "m11",
        "Kinbozan": "m13",
        "Shishi": "m10",
        "Kazuma": "j",
        "Onokatsu": "j",
        "Asakoryu": "m14",
        "Daiseizan": "j"
      },
      "bonus": []
    },
    {
      "key": "gumbai",
      "name": "Gumbai",
      "ranks": {
        "Hoshoryu": "y",
        "Onosato": "y",
        "Kirishima": "o",
        "Kotozakura": "o",
        "Atamifuji": "s",
        "Kotoshoho": "m1",
        "Aonishiki": "s",
        "Wakatakakage": "m6",
        "Oho": "m8",
        "Yoshinofuji": "m2",
        "Fujinokawa": "k",
        "Takanosho": "m4",
        "Churanoumi": "m3",
        "Gonoyama": "m3",
        "Hakunofuji": "k",
        "Hiradoumi": "m10",
        "Daieisho": "m1",
        "Ichiyamamoto": "m7",
        "Oshoma": "m6",
        "Ura": "m10",
        "Fujiseiun": "m7",
        "Shodai": "m11",
        "Kotoeiho": "m2",
        "Takayasu": "m2",
        "Roga": "m5",
        "Wakamotoharu": "m11",
        "Fujiryoga": "m4",
        "Tobizaru": "m14",
        "Asanoyama": "m7",
        "Chiyoshoma": "m15",
        "Mitakeumi": "j",
        "Wakanosho": "m12",
        "Abi": "m13",
        "Asahakuryu": "m13",
        "Nishikifuji": "m8",
        "Takerufuji": "m8",
        "Kinbozan": "m11",
        "Shishi": "m9",
        "Kazuma": "j",
        "Onokatsu": "j",
        "Asakoryu": "m13",
        "Daiseizan": "j"
      },
      "bonus": []
    }
  ]
};
